definitions:
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Cat:
    properties:
      breed:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      experience:
        type: integer
      id:
        type: integer
      name:
        type: string
      salary:
        type: number
      updatedAt:
        type: string
    type: object
  models.Mission:
    properties:
      cat_id:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      is_complete:
        type: boolean
      targets:
        items:
          $ref: '#/definitions/models.Target'
        type: array
      updatedAt:
        type: string
    type: object
  models.Target:
    properties:
      country:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      is_complete:
        type: boolean
      mission_id:
        type: integer
      name:
        type: string
      notes:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /cats:
    get:
      description: Get a list of all cats in the database
      responses:
        "200":
          description: List of cats
          schema:
            items:
              $ref: '#/definitions/models.Cat'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get list of all cats
    post:
      description: Create a new cat and store it in the database
      parameters:
      - description: Cat data
        in: body
        name: cat
        required: true
        schema:
          $ref: '#/definitions/models.Cat'
      responses:
        "201":
          description: Successfully created cat
          schema:
            $ref: '#/definitions/models.Cat'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new cat
    put:
      description: Update an existing cat's details
      parameters:
      - description: Updated cat data
        in: body
        name: cat
        required: true
        schema:
          $ref: '#/definitions/models.Cat'
      responses:
        "200":
          description: Successfully updated cat
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Update a cat
  /cats/{id}:
    delete:
      description: Delete a cat from the database by its ID
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Successfully deleted cat
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Delete a cat
    get:
      description: Get a specific cat by its ID
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Cat data
          schema:
            $ref: '#/definitions/models.Cat'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get cat by ID
  /missions:
    get:
      description: Get a list of all missions in the database
      responses:
        "200":
          description: List of missions
          schema:
            items:
              $ref: '#/definitions/models.Mission'
            type: array
        "404":
          description: Missions not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get list of all missions
    post:
      description: Create a new mission and store it in the database
      parameters:
      - description: Mission data
        in: body
        name: mission
        required: true
        schema:
          $ref: '#/definitions/models.Mission'
      responses:
        "201":
          description: Successfully created mission
          schema:
            $ref: '#/definitions/models.Mission'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new mission
  /missions/{id}:
    delete:
      description: Delete a mission by its ID
      parameters:
      - description: Mission ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Successfully deleted mission
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Delete a mission
    get:
      description: Get a specific mission by its ID
      parameters:
      - description: Mission ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Mission data
          schema:
            $ref: '#/definitions/models.Mission'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Mission not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get mission by ID
  /missions/{mission_id}/cats/{cat_id}:
    post:
      description: Assign a cat to a specific mission
      parameters:
      - description: Mission ID
        in: path
        name: mission_id
        required: true
        type: integer
      - description: Cat ID
        in: path
        name: cat_id
        required: true
        type: integer
      responses:
        "200":
          description: Successfully assigned cat to mission
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Assign a cat to a mission
  /missions/{mission_id}/targets:
    post:
      description: Add a target to a specific mission
      parameters:
      - description: Mission ID
        in: path
        name: mission_id
        required: true
        type: integer
      - description: Target data
        in: body
        name: target
        required: true
        schema:
          $ref: '#/definitions/models.Target'
      responses:
        "201":
          description: Successfully added target to mission
          schema:
            $ref: '#/definitions/models.Target'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Add a target to a mission
  /missions/status:
    put:
      description: Update the status of an existing mission
      parameters:
      - description: Updated mission data
        in: body
        name: mission
        required: true
        schema:
          $ref: '#/definitions/models.Mission'
      responses:
        "200":
          description: Successfully updated mission status
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Update mission status
  /targets/{id}:
    delete:
      description: Delete a target by its ID
      parameters:
      - description: Target ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Successfully deleted target
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Delete a target
  /targets/{id}/status:
    put:
      description: Update the status of a specific target
      parameters:
      - description: Target ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Target status updated successfully
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Update target status
  /targets/{target_id}/notes:
    put:
      description: Update notes for a specific target
      parameters:
      - description: Target ID
        in: path
        name: target_id
        required: true
        type: integer
      - description: Target notes data
        in: body
        name: target
        required: true
        schema:
          $ref: '#/definitions/models.Target'
      responses:
        "200":
          description: Target notes updated successfully
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Update target notes
swagger: "2.0"
